/// DO NOT EDIT THIS FILE
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY GrinderPlus
import 'dart:convert' show json;

final pubSpec = json.decode('{"name":"grinder_test","version":"1.0.0+2","environment":{"sdk":">=2.17.7 <3.0.0"},"description":"A sample command-line application.","dev_dependencies":{"grinder":"^0.9.2","lints":"^2.0.0","grinder_plus":{"path":"../../skc/grinder_plus"}}}');
